In [40]:
import sqlite3
import pandas as pd
import datetime

In [41]:
conn = sqlite3.connect('../scraper/data/ads_storage.db')
cursor = conn.cursor()
# Fetch all processed data
cursor.execute("SELECT * FROM ads_raw WHERE status = 'done'")
columns = [description[0] for description in cursor.description]
rows = cursor.fetchall()

# Convert to DataFrame
conn.close()
df = pd.DataFrame(rows, columns=columns)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6221 entries, 0 to 6220
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hash_id           6221 non-null   str
 1   title             6221 non-null   str
 2   link              6221 non-null   str
 3   price_m2_eur      6130 non-null   str
 4   price_m2_bgn      6130 non-null   str
 5   size_m2           6134 non-null   str
 6   description       6221 non-null   str
 7   floor             5563 non-null   str
 8   akt16             5276 non-null   str
 9   energy_class      5574 non-null   str
 10  potreblenie       5574 non-null   str
 11  broker_commision  6106 non-null   str
 12  additional_notes  6134 non-null   str
 13  status            6221 non-null   str
 14  created_at        6221 non-null   str
 15  last_updated      6221 non-null   str
dtypes: str(16)
memory usage: 777.8 KB

In [42]:
df.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,floor,akt16,energy_class,potreblenie,broker_commision,additional_notes,status,created_at,last_updated
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,3 333,6 519.43,12,"Строително-инвестиционна компания Идея Хоум, п...",,Да,NaN,NaN,Не,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:14.999578,2026-02-16 16:43:51.616580
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,78,152.78,896,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,NaN,NaN,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008348,2026-02-16 17:08:29.392911
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,2 835,5 545.72,31,"Dotwon Real Estate, част от Dotwon Group, пред...",0 от 7,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008562,2026-02-16 17:08:29.394527
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1 888,3 692.13,49,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,1 от 6,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008903,2026-02-16 17:08:29.394702
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1 745,3 413.81,55,След основен ремонт. Едностаен апартамент в ту...,2 от 3,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.009103,2026-02-16 17:08:29.394804

In [43]:
df["status"].unique().tolist()

['done']

In [44]:
df["price_m2_eur"]

0       3 333
1          78
2       2 835
3       1 888
4       1 745
        ...
6216    2 680
6217    2 361
6218    2 380
6219    2 500
6220    2 611
Name: price_m2_eur, Length: 6221, dtype: str

###  Transform the columns to the appropriate format

In [45]:
df.loc[0, "price_m2_eur"].strip()

'3 333'

In [46]:
df.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,floor,akt16,energy_class,potreblenie,broker_commision,additional_notes,status,created_at,last_updated
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,3 333,6 519.43,12,"Строително-инвестиционна компания Идея Хоум, п...",,Да,NaN,NaN,Не,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:14.999578,2026-02-16 16:43:51.616580
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,78,152.78,896,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,NaN,NaN,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008348,2026-02-16 17:08:29.392911
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,2 835,5 545.72,31,"Dotwon Real Estate, част от Dotwon Group, пред...",0 от 7,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008562,2026-02-16 17:08:29.394527
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1 888,3 692.13,49,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,1 от 6,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008903,2026-02-16 17:08:29.394702
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1 745,3 413.81,55,След основен ремонт. Едностаен апартамент в ту...,2 от 3,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.009103,2026-02-16 17:08:29.394804

In [47]:
cols_to_strip = ["price_m2_eur", "price_m2_bgn"]
df_copy = df.copy()
df_copy[cols_to_strip] = df_copy[cols_to_strip].apply(lambda row: row.str.replace(" ", ""))
df_copy[cols_to_strip] = df_copy[cols_to_strip].astype(float)
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 6221 entries, 0 to 6220
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hash_id           6221 non-null   str
 1   title             6221 non-null   str
 2   link              6221 non-null   str
 3   price_m2_eur      6130 non-null   float64
 4   price_m2_bgn      6130 non-null   float64
 5   size_m2           6134 non-null   str
 6   description       6221 non-null   str
 7   floor             5563 non-null   str
 8   akt16             5276 non-null   str
 9   energy_class      5574 non-null   str
 10  potreblenie       5574 non-null   str
 11  broker_commision  6106 non-null   str
 12  additional_notes  6134 non-null   str
 13  status            6221 non-null   str
 14  created_at        6221 non-null   str
 15  last_updated      6221 non-null   str
dtypes: float64(2), str(14)
memory usage: 777.8 KB

In [ ]:
# 1. convert the price & size columns to float
def convert_strip_and_convert_to_numeric(df: pd.DataFrame, cols_to_strip: list)->pd.DataFrame:
    df[cols_to_strip] = df[cols_to_strip].apply(lambda row: row.str.replace(" ", ""))
    df[cols_to_strip] = df[cols_to_strip].astype(float)
    return df

cols_to_strip = ["price_m2_eur", "price_m2_bgn"]
df_copy = df.copy()
df_copy = convert_strip_and_convert_to_numeric(df_copy, cols_to_strip)
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 6221 entries, 0 to 6220
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hash_id           6221 non-null   str
 1   title             6221 non-null   str
 2   link              6221 non-null   str
 3   price_m2_eur      6130 non-null   float64
 4   price_m2_bgn      6130 non-null   float64
 5   size_m2           6134 non-null   str
 6   description       6221 non-null   str
 7   floor             5563 non-null   str
 8   akt16             5276 non-null   str
 9   energy_class      5574 non-null   str
 10  potreblenie       5574 non-null   str
 11  broker_commision  6106 non-null   str
 12  additional_notes  6134 non-null   str
 13  status            6221 non-null   str
 14  created_at        6221 non-null   str
 15  last_updated      6221 non-null   str
dtypes: float64(2), str(14)
memory usage: 777.8 KB

In [60]:
import re 

match = re.search(r'\d+', str("11 ot 25"))
print(match.group())

11

In [61]:
import numpy as np

# 2. Extract the floor number from the floor column
def extract_floor_number(floor_string: str):
    if pd.isna(floor_string):
        return np.nan
    
    match = re.search(r'\d+', str(floor_string))
    return int(match.group()) if match else np.nan

df_copy["floor_clean"] = df_copy["floor"].apply(extract_floor_number)
df_copy = df_copy.drop(labels="floor", axis=1)
df_copy.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,akt16,energy_class,potreblenie,broker_commision,additional_notes,status,created_at,last_updated,floor_clean
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,3333.0,6519.43,12,"Строително-инвестиционна компания Идея Хоум, п...",Да,NaN,NaN,Не,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:14.999578,2026-02-16 16:43:51.616580,NaN
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,78.0,152.78,896,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,NaN,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008348,2026-02-16 17:08:29.392911,NaN
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,2835.0,5545.72,31,"Dotwon Real Estate, част от Dotwon Group, пред...",Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008562,2026-02-16 17:08:29.394527,0.0
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1888.0,3692.13,49,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008903,2026-02-16 17:08:29.394702,1.0
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1745.0,3413.81,55,След основен ремонт. Едностаен апартамент в ту...,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.009103,2026-02-16 17:08:29.394804,2.0

In [64]:
df["broker_commision"].unique().tolist()

['Не', 'Да', nan]

In [67]:
# 3. convert the yes/no columns to bool
def convert_to_bool(value: str):
    if pd.isna(value):
        return np.nan
    
    elif value.upper() == "ДА":
        return True

    else:
        return False

bool_cols = ["akt16", "broker_commision"]
for col in bool_cols:
    df_copy[f"{col}_processed"] = df_copy[f"{col}"].apply(convert_to_bool)
    df_copy.drop(labels=col, axis=1, inplace=True)

df_copy.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,energy_class,potreblenie,additional_notes,status,created_at,last_updated,floor_clean,akt16_processed,broker_commision_processed
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,3333.0,6519.43,12,"Строително-инвестиционна компания Идея Хоум, п...",NaN,NaN,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:14.999578,2026-02-16 16:43:51.616580,NaN,True,False
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,78.0,152.78,896,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008348,2026-02-16 17:08:29.392911,NaN,NaN,True
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,2835.0,5545.72,31,"Dotwon Real Estate, част от Dotwon Group, пред...",N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008562,2026-02-16 17:08:29.394527,0.0,True,True
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1888.0,3692.13,49,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008903,2026-02-16 17:08:29.394702,1.0,True,True
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1745.0,3413.81,55,След основен ремонт. Едностаен апартамент в ту...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.009103,2026-02-16 17:08:29.394804,2.0,True,True

In [70]:
df_copy.loc[3, "link"]

'https://www.imoti.net/bg/obiava/prodava/sofia/ovcha-kupel/ednostaen/6176507/?sid=icNBCK&page=1'